name: Sui-Prover Test Action

on: [pull_request]

jobs:
  build:
    runs-on: macos-latest
    env: 
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    concurrency:
      group: ${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Homebrew
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/Homebrew
            /usr/local/Homebrew
            /opt/homebrew
          key: brew-macos-dotnet8-z3-rust
          restore-keys: |
            brew-macos-

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Install dependencies from formula & build prover
        run: |
          sh ./crates/sui-prover/tests/sui-prover.sh

      - name: Upload Prover Binary
        uses: actions/upload-artifact@v4
        with:
          name: sui-prover-binary
          path: ~/.local/libexec/sui-prover/bin/sui-prover

      - name: Upload Boogie Binaries
        uses: actions/upload-artifact@v4
        with:
          name: boogie-artifacts
          path: ~/.local/bin/boogie

  # internal-tests:
  #   runs-on: macos-latest
  #   needs: build
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Run Tests
  #       run: |
  #         cd ./crates/sui-prover
  #         cargo test 

  sui-kit-tests:
    runs-on: macos-latest
    needs: build
    steps:
      - name: Download prover binary
        uses: actions/download-artifact@v4
        with:
          name: sui-prover-binary
          path: ${{ github.workspace }}/bin
      - name: Download boogie binaries
        uses: actions/download-artifact@v4
        with:
          name: boogie-artifacts
          path: ${{ github.workspace }}/bin/boogie

      - name: Make binary executable
        run: |
          chmod +x ${{ github.workspace }}/bin/sui-prover
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Checkout Repo
        run: |
          git clone https://github.com/asymptotic-code/sui-kit.git sui-kit
     
      - name: Run Amm Tests
        run: |
          chmod +x ${{ github.workspace }}/bin/boogie
          ls -l ${{ github.workspace }}/bin/boogie

          export DOTNET_ROOT="$(brew --prefix dotnet@8)/libexec"
          export BOOGIE_EXE="${{ github.workspace }}/bin/boogie"
          export Z3_EXE="$(brew --prefix z3)/bin/z3"

          cd sui-kit/examples/amm
          sui-prover -s 2
      
      - name: Run Showcase Tests
        run: |
          cd sui-kit/examples/showcase
          sui-prover -s 2

      - name: Run Guide Tests
        run: |
          cd sui-kit/examples/guide
          sui-prover -s 2
  
  # integer-mate-tests:
  #   runs-on: macos-latest
  #   needs: build
  #   steps:
  #     - name: Checkout Repo
  #       run: |
  #         git clone https://github.com/asymptotic-code/integer-library int-lib
  #         cd int-lib
     
  #     - name: Run Regular Tests
  #       run: |
  #         cd specs
  #         sui-prover -s 2
  #         cd ..
      
  #     - name: Run BV Tests
  #       run: |
  #         cd specs-bv
  #         sui-prover -s 2 --no-bv-int-encoding
  #         cd ..
