name: Sui-Prover Test Action

on: [pull_request]

jobs:
  build-prover:
    runs-on: macos-latest

    concurrency:
      group: build-prover-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true

    outputs:
      artifact-name: ${{ steps.set-artifact.outputs.name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "sui-prover"
          cache-targets: true

      - name: Cache Boogie
        uses: actions/cache@v4
        with:
          path: ~/.local/libexec/sui-prover
          key: boogie-${{ runner.os }}-
          restore-keys: |
            boogie-${{ runner.os }}

      - name: Install dependencies and build prover
        run: |
          sh ./crates/sui-prover/tests/sui-prover.sh

      - name: Set artifact name
        id: set-artifact
        run: echo "name=sui-prover-${{ github.run_id }}" >> $GITHUB_OUTPUT

      - name: Prepare artifact bundle
        run: |
          mkdir -p ~/artifact-bundle/bin
          mkdir -p ~/artifact-bundle/z3
          mkdir -p ~/artifact-bundle/boogie

          # Copy sui-prover binary
          cp target/release/sui-prover ~/artifact-bundle/bin/

          # Copy boogie executable and all its dependencies
          cp -r ~/.local/libexec/sui-prover/* ~/artifact-bundle/boogie/
          ln -s ~/artifact-bundle/boogie/BoogieDriver ~/artifact-bundle/bin/boogie

          # Copy Z3 (just the bin directory is needed)
          cp -r "$(brew --prefix z3)/bin" ~/artifact-bundle/z3/

      - name: Upload prover binary and dependencies
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set-artifact.outputs.name }}
          path: ~/artifact-bundle
          retention-days: 1
          if-no-files-found: error
          compression-level: 6

      - name: Verify installation
        run: |
          chmod +x ~/artifact-bundle/bin/sui-prover
          chmod +x ~/artifact-bundle/bin/boogie

          ~/artifact-bundle/bin/sui-prover --version
          ~/artifact-bundle/bin/boogie /version

  kit-specs:
    needs: build-prover
    runs-on: macos-latest

    concurrency:
      group: kit-specs-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true

    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-prover.outputs.artifact-name }}
          path: ~/prover-bundle

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true

      - name: Setup
        run: |
          mkdir -p ~/.local/bin

          cp ~/prover-bundle/bin/sui-prover ~/.local/bin/
          ln -s ~/prover-bundle/boogie/BoogieDriver ~/.local/bin/boogie

          chmod +x ~/.local/bin/boogie
          chmod +x ~/.local/bin/sui-prover
          chmod +x ~/prover-bundle/z3/bin/z3

          # Add to PATH
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/prover-bundle/z3/bin" >> $GITHUB_PATH

          echo "DOTNET_ROOT=/usr/local/share/dotnet" >> $GITHUB_ENV
          echo "BOOGIE_EXE=$HOME/.local/bin/boogie" >> $GITHUB_ENV
          echo "Z3_EXE=$HOME/prover-bundle/z3/bin/z3" >> $GITHUB_ENV

      - name: Run
        run: |
          git clone https://github.com/asymptotic-code/sui-kit.git sui-kit

          cd sui-kit/examples/amm
          sui-prover

          cd ../showcase
          sui-prover

          cd ../guide
          sui-prover

  internal-tests:
    # check if prover needed
    needs: build-prover
    runs-on: macos-latest

    concurrency:
      group: internal-tests-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-prover.outputs.artifact-name }}
          path: ~/prover-bundle

      - name: Setup
        run: |
          mkdir -p ~/.local/bin

          cp ~/prover-bundle/bin/sui-prover ~/.local/bin/
          ln -s ~/prover-bundle/boogie/BoogieDriver ~/.local/bin/boogie

          chmod +x ~/.local/bin/boogie
          chmod +x ~/.local/bin/sui-prover
          chmod +x ~/prover-bundle/z3/bin/z3

          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/prover-bundle/z3/bin" >> $GITHUB_PATH

          echo "DOTNET_ROOT=/usr/local/share/dotnet" >> $GITHUB_ENV
          echo "BOOGIE_EXE=$HOME/.local/bin/boogie" >> $GITHUB_ENV
          echo "Z3_EXE=$HOME/prover-bundle/z3/bin/z3" >> $GITHUB_ENV

      - name: Run
        run: |
          cd ./crates/sui-prover
          cargo test

  integer-mate-specs:
    needs: build-prover
    runs-on: macos-latest

    concurrency:
      group: integer-mate-specs-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true

    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-prover.outputs.artifact-name }}
          path: ~/prover-bundle

      - name: Setup
        run: |
          mkdir -p ~/.local/bin

          cp ~/prover-bundle/bin/sui-prover ~/.local/bin/
          ln -s ~/prover-bundle/boogie/BoogieDriver ~/.local/bin/boogie

          chmod +x ~/.local/bin/boogie
          chmod +x ~/.local/bin/sui-prover
          chmod +x ~/prover-bundle/z3/bin/z3

          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/prover-bundle/z3/bin" >> $GITHUB_PATH

          echo "DOTNET_ROOT=/usr/local/share/dotnet" >> $GITHUB_ENV
          echo "BOOGIE_EXE=$HOME/.local/bin/boogie" >> $GITHUB_ENV
          echo "Z3_EXE=$HOME/prover-bundle/z3/bin/z3" >> $GITHUB_ENV

      - name: Run
        run: |
          git clone https://github.com/asymptotic-code/integer-library int-lib

          cd int-lib/specs
          sui-prover

          cd ../specs-bv
          sui-prover --no-bv-int-encoding

  token-distribution-specs:
    needs: build-prover
    runs-on: macos-latest

    concurrency:
      group: token-distribution-specs-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true

    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-prover.outputs.artifact-name }}
          path: ~/prover-bundle

      - name: Setup
        run: |
          mkdir -p ~/.local/bin

          cp ~/prover-bundle/bin/sui-prover ~/.local/bin/
          ln -s ~/prover-bundle/boogie/BoogieDriver ~/.local/bin/boogie

          chmod +x ~/.local/bin/boogie
          chmod +x ~/.local/bin/sui-prover
          chmod +x ~/prover-bundle/z3/bin/z3

          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/prover-bundle/z3/bin" >> $GITHUB_PATH

          echo "DOTNET_ROOT=/usr/local/share/dotnet" >> $GITHUB_ENV
          echo "BOOGIE_EXE=$HOME/.local/bin/boogie" >> $GITHUB_ENV
          echo "Z3_EXE=$HOME/prover-bundle/z3/bin/z3" >> $GITHUB_ENV

      - name: Run
        run: |
          git clone --depth 1 -b fix/prover_specs https://github.com/asymptotic-code/sui-smart-contracts.git sui-smart-contracts
          cd sui-smart-contracts/token-distribution-specs 
          sui-prover

  scallop-bpl-generation:
    needs: build-prover
    runs-on: macos-latest

    concurrency:
      group: scallop-bpl-generation-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true

    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-prover.outputs.artifact-name }}
          path: ~/prover-bundle

      - name: Setup
        run: |
          mkdir -p ~/.local/bin

          cp ~/prover-bundle/bin/sui-prover ~/.local/bin/
          ln -s ~/prover-bundle/boogie/BoogieDriver ~/.local/bin/boogie

          chmod +x ~/.local/bin/boogie
          chmod +x ~/.local/bin/sui-prover
          chmod +x ~/prover-bundle/z3/bin/z3

          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/prover-bundle/z3/bin" >> $GITHUB_PATH

          echo "DOTNET_ROOT=/usr/local/share/dotnet" >> $GITHUB_ENV
          echo "BOOGIE_EXE=$HOME/.local/bin/boogie" >> $GITHUB_ENV
          echo "Z3_EXE=$HOME/prover-bundle/z3/bin/z3" >> $GITHUB_ENV

      - name: Clone scallop repo
        uses: actions/checkout@v4
        with:
          repository: asymptotic-code/scallop-lending
          ref: specs
          token: ${{ secrets.PAT_TOKEN }}
          path: scallop

      - name: Run
        run: |
          cd scallop/contracts/specs
          sui-prover -g

  cetus-bpl-generation:
    needs: build-prover
    runs-on: macos-latest

    concurrency:
      group: cetus-bpl-generation-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true

    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-prover.outputs.artifact-name }}
          path: ~/prover-bundle

      - name: Setup
        run: |
          mkdir -p ~/.local/bin

          cp ~/prover-bundle/bin/sui-prover ~/.local/bin/
          ln -s ~/prover-bundle/boogie/BoogieDriver ~/.local/bin/boogie

          chmod +x ~/.local/bin/boogie
          chmod +x ~/.local/bin/sui-prover
          chmod +x ~/prover-bundle/z3/bin/z3

          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/prover-bundle/z3/bin" >> $GITHUB_PATH

          echo "DOTNET_ROOT=/usr/local/share/dotnet" >> $GITHUB_ENV
          echo "BOOGIE_EXE=$HOME/.local/bin/boogie" >> $GITHUB_ENV
          echo "Z3_EXE=$HOME/prover-bundle/z3/bin/z3" >> $GITHUB_ENV

      - name: Clone cetus repo
        uses: actions/checkout@v4
        with:
          repository: asymptotic-code/cetus-clmm
          ref: clmm-specs
          token: ${{ secrets.PAT_TOKEN }}
          path: cetus    

      - name: Run
        run: |
          cd cetus/cetus_clmm_specs
          sui-prover -g
